name: Create a comment on new issues
on:
  issues:
    types: [opened]
jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name:  Create Comment
        uses:  ghActionDemo/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.issue.number}}
          body:  |
            This is multi-line comment
            -  Created by [create-or-update-comment] [1]

            [1]:  https://github.com/GITTeammember1/ghActionDemo/create-or-update-comment reactions: '+1'
